/**
 * Created by luke on 01/08/22.
 */
Ext.define('stver.model.forms.mese.GridModel', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'id', type: 'string'},
        {name: 'mese', type: 'string'},
        {name: 'codart', type: 'string'},
        {name: 'descrizione',type: 'string'},
        {name: 'pianificatore',type: 'string'},
        {name: 'g1',type: 'float'},
        {name: 'g2',type: 'float'},
        {name: 'g3',type: 'float'},
        {name: 'g4',type: 'float'},
        {name: 'g5',type: 'float'},
        {name: 'g6',type: 'float'},
        {name: 'g7',type: 'float'},
        {name: 'g8',type: 'float'},
        {name: 'g9',type: 'float'},
        {name: 'g10',type: 'float'},
        {name: 'g11',type: 'float'},
        {name: 'g12',type: 'float'},
        {name: 'g13',type: 'float'},
        {name: 'g14',type: 'float'},
        {name: 'g15',type: 'float'},
        {name: 'g16',type: 'float'},
        {name: 'g17',type: 'float'},
        {name: 'g18',type: 'float'},
        {name: 'g19',type: 'float'},
        {name: 'g20',type: 'float'},
        {name: 'g21',type: 'float'},
        {name: 'g22',type: 'float'},
        {name: 'g23',type: 'float'},
        {name: 'g24',type: 'float'},
        {name: 'g25',type: 'float'},
        {name: 'g26',type: 'float'},
        {name: 'g27',type: 'float'},
        {name: 'g28',type: 'float'},
        {name: 'g29',type: 'float'},
        {name: 'g30',type: 'float'},
        {name: 'g31',type: 'float'},
        {name: 'totmese',type: 'float'}
    ]
});