Ext.define('skd.view.main.Model', {
    extend: 'portal.v1.view.main.ViewModel',
    alias: 'viewmodel.main',

    requires: [
        'skd.store.forms.filtri.ComboCdl',
        'skd.store.forms.filtri.ComboComponent',
        'skd.store.forms.filtri.ComboGiacenza',
        'skd.store.forms.filtri.ComboLab',
        'skd.store.forms.filtri.ComboNote',
        'skd.store.forms.filtri.ComboOdp',
        'skd.store.forms.filtri.ComboOperatore',
        'skd.store.forms.filtri.ComboOperazione',
        'skd.store.forms.filtri.ComboOrder',
        'skd.store.forms.filtri.ComboPart',
        'skd.store.forms.filtri.ComboReparto',
        'skd.store.forms.filtri.ComboStato',
        'skd.store.forms.filtri.GridCdl',
        'skd.store.forms.filtri.GridComponent',
        'skd.store.forms.filtri.GridLab',
        'skd.store.forms.filtri.GridNote',
        'skd.store.forms.filtri.GridOdp',
        'skd.store.forms.filtri.GridOperatore',
        'skd.store.forms.filtri.GridOperazione',
        'skd.store.forms.filtri.GridOrder',
        'skd.store.forms.filtri.GridPart',
        'skd.store.forms.filtri.GridReparto',
        'skd.store.forms.filtri.GridStato',
    ],
    stores: {
        storeComboGiacenza: { type: 'comboGiacenza', autoLoad: true },
        storeComboStato: { type: 'comboStato', autoLoad: true },
        storeComboLab: { type: 'comboLab' },
        storeComboNote: { type: 'comboNote' },
        storeComboPart: { type: 'comboPart' },
        storeComboComponent: { type: 'comboComponent' },
        storeComboOrder: { type: 'comboOrder' },
        storeComboReparto: { type: 'comboReparto' },
        storeComboCdl: { type: 'comboCdl' },
        storeComboOperatore: { type: 'comboOperatore' },
        storeComboOdp: { type: 'comboOdp' },
        storeComboOperazione: { type: 'comboOperazione' },

        storeGridLab: { type: 'gridLab-filtri' },
        storeGridLabCdl: { type: 'gridLab-filtri' },
        storeGridNote: { type: 'gridNote-filtri' },
        storeGridPart: { type: 'gridPart-filtri' },
        storeGridComponent: { type: 'gridComponent-filtri' },
        storeGridOrder: { type: 'gridOrder-filtri' },
        storeGridReparto: { type: 'gridReparto-filtri' },
        storeGridCdlReparto: { type: 'gridReparto-filtri' },
        storeGridCdlCdl: { type: 'gridCdl-filtri' },
        storeGridCdl: { type: 'gridCdl-filtri' },
        storeGridOperatore: { type: 'gridOperatore-filtri' },
        storeGridOperazione: { type: 'gridOperazione-filtri' },
        storeGridPreparatore: { type: 'gridOperazione-filtri' },
        storeGridStato: { type: 'gridStato-filtri' },
        storeGridOdp: { type: 'gridOdp-filtri' },
        storeGridOdpCdl: { type: 'gridOdp-filtri' }
    },
    data: {
        name: 'skd',
        tr: LOCALE.default,
        apptitle: Locale.t('skd.apptitle'),
        tag: 'SKD',
        titleInfo: 'Caricamento in corso.....',
        gridActive: null,
        westShow: false,
        connection: '',
        filtri: {},
        filtriCdl: {},
        filtriMancanti: {
            operatore: ['a', 'b']
        },
        iconFiltri: 'fas fa-caret-square-down',
        iconFiltriCdl: 'fas fa-caret-square-down',
        valueOrderCdl: 'data_ordine_cliente',
        textOrderCdl: 'Ordinato per ordine cliente',
        selectCell: null,
        infoCell: null,
        row: null,
        hiddenPdf: true,
        hiddenInfo: true
    }
});
