/**
 * Created by fabrizio on 20/02/18.
 */
Ext.define('skd.view.forms.cruscotto.TestataOdp', {
    extend: 'Ext.form.Panel',
    // xtype: 'pianificazione',
    requires:[
        'Ext.form.field.Display',
        'Ext.layout.container.HBox'
    ],
    // posizione:'pianificazione',
    items:[
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_proposed_location'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_proposed_location}'
            }
        },
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_need_date'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_need_date}'
            }
        },
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_earliest_start_date'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_earliest_start_date}'
            }
        },
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_eng_chg_level'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_eng_chg_level}'
            }
        },
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_routing_revision'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_routing_revision}'
            }
        },
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_objstate'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_objstate}'
            }
        },
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_revised_qty_due'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_revised_qty_due}'
            }
        },
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_qty_complete'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_qty_complete}'
            }
        },
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_res_ordine'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_res_ordine}'
            }
        },
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_order_no'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_order_no}'
            }
        },
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_release_no'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_release_no}'
            }
        },
        {
            xtype:'displayfield',
            fieldLabel:Locale.t('skd.forms.cruscotto.testataodp.fields.sc_op_sequence_no'),
            userCls:'label_cruscotto',
            bind:{
                value:'{testataOdp.sc_op_sequence_no}'
            }
        }
    ],
    listeners:{
        collapse:'onTogleCollapse',
        expand:'onTogleCollapse'
    }
});